Add Block Device Support
raspberrypi/picotool pull request #191
Opened 2024-12-18 17:50 UTC by will-v-pi

Adds support for using `ls`, `mkdir`, `cp` (including between host and device), `rm`, and `cat` commands, with LittleFS (used by MicroPython) or FatFS filesystem support.

Works with block devices specified in the binary info, and with partitions. It autodetects the file system if `--filesystem` is not specified, and also supports formatting the block device if required with the `-f` argument.

This fixes #58

2025-08-25 07:14 UTC, lurch commented on README.md
> +            The file name
"dirname" vs. "file name" ? :wink: 
Also, if I wanted to list the "root directory" would I give it a `<dirname>` of `/`, or something else?

2025-08-25 07:16 UTC, lurch commented on README.md
> +            The file name
```suggestion
        <dirname>
            The directory name
```

2025-08-25 07:19 UTC, lurch commented on README.md
> +        -f, --format
Hmmm, we now seem to have **BOTH** `-f, --format` and `-f, --force` flags?! Either this worn't work properly, or if it does work it's pretty confusing!

2025-08-25 07:22 UTC, lurch commented on README.md
> +Copy file to/from the block device - use :filename to indicate files on the device (eg `cp main.py :main.py` to upload to the device)
Probably doesn't hurt to be explicit?
```suggestion
Copy file to/from the block device - use :filename to indicate files on the device (e.g. `cp main.py :main.py` to upload to the device, or `cp :main.py main.py` to download from the device)
```

2025-08-25 07:29 UTC, lurch commented on README.md
> +Copy file to/from the block device - use :filename to indicate files on the device (eg `cp main.py :main.py` to upload to the device)
* Does this `bdev cp` command check that one (and only one) of either `src` or `dest` starts with a colon?
* Does it only work for files and not directories?
* If the answer to the previous question is "only files", would it be a lot of additional work to be able to copy directories? (which would presumably need to operate recursively)

2025-08-25 07:34 UTC, lurch commented on lib/littlefs/README.md
> +The current files come from v2.8.2
_Maybe_ worth bumping (after testing, of course) to the latest release? https://github.com/littlefs-project/littlefs/releases/tag/v2.11.1

2025-08-25 07:50 UTC, lurch commented on main.cpp
> +            optional_untyped_file_selection_x("dirname", 0) +
Does the `optional_` here indicate that this is an optional argument? If so, it should probably appear in the `README.md` as `[dirname]` rather than `<dirname>` ?

2025-08-25 07:55 UTC, lurch commented on main.cpp
> +                    // Do automatically erase flash, and make it aligned
```suggestion
                    // To automatically erase flash, and make it aligned
```
?

2025-08-25 08:11 UTC, lurch commented on main.cpp
> +                // Check if we need to erase (ie check for non 0xff)
AIUI, when you erase Flash it sets it to all-1s, and so when you "write data" to Flash, it only flips some of the 1s to 0s. So I guess that _theoretically_, if you're overwriting `0b11111110` with `0b11111100` then there's also no need to erase the Flash first? Which suggests we could do something more sophisticated here than just "check for non 0xff" ? :thinking:

2025-08-25 08:35 UTC, will-v-pi commented on README.md
> +            The file name
Just pass no `dirname`, like you would to the normal `ls` command - it’s an optional argument

2025-08-25 08:35 UTC, will-v-pi commented on README.md
> +        -f, --format
Good spot - I’ll make this filesystem one not have a short argument

2025-08-25 08:37 UTC, will-v-pi commented on README.md
> +Copy file to/from the block device - use :filename to indicate files on the device (eg `cp main.py :main.py` to upload to the device)
- No - you can copy a file to somewhere else on the device, or even use this to copy local files if you really wanted
- Yes, it only works for files
- Could probably add that - just needs a recursive walk like `ls` has

2025-08-25 08:40 UTC, will-v-pi commented on main.cpp
> +            optional_untyped_file_selection_x("dirname", 0) +
Yes, it’s optional - I’m not sure why the CLI stuff isn’t putting square brackets around it

2025-08-25 08:42 UTC, will-v-pi commented on main.cpp
> +                    // Do automatically erase flash, and make it aligned
The comments were meant to mean “Check if we want to erase” followed by “Yes, we do want erase” - so maybe just delete the “Do”?
```suggestion
                    // Automatically erase flash, and make it aligned
```

2025-08-25 08:45 UTC, will-v-pi commented on main.cpp
> +                // Check if we need to erase (ie check for non 0xff)
That’s true, I could probably check for `write_data & ~current_data` instead

2025-08-25 08:47 UTC, lurch commented on main.cpp
> +    fos << "Copying " << (srcRemote ? "device " : "local ") << settings.filenames[0] << " to " << (destRemote ? "device " : "local ") << settings.filenames[1] << "\n";
Perhaps it's worth checking that `(srcRemote || destRemote)`, as there seems to be little point using `picotool bdev cp` to copy one local file to another local file? :wink:

2025-08-25 08:50 UTC, lurch commented on main.cpp
> +        data_buf.resize(size);
If you accidentally point this at the wrong local filename (e.g. a huge disk-image file), is there a risk that this might cause an out-of-memory error?

2025-08-25 08:57 UTC, lurch commented on README.md
> +Print contents of file on the block device
Will an appropriate error get displayed if you try to `bdev cat` a directory name?

2025-08-25 08:59 UTC, lurch commented on README.md
> +        -f, --format
(perhaps the arg-parsing library could/should raise an error if given the same argument multiple times?)

2025-08-25 09:13 UTC, lurch commented
A thought I just had - to make this slightly easier to use, could you have `picotool` check what filename it was invoked with (e.g. like `busybox` does), and then you could have `picotool_ls`, `picotool_cat`, etc. symlinks to the `picotool` binary, and then calling `picotool_ls somedir` would do the same thing as `picotool bdev ls somedir` ? (Or if that's not possible, perhaps the picotool CMake install could add a bunch of shell scripts e.g. named `picotool_ls` which just does `picotool bdev ls $@`)

2025-08-25 09:19 UTC, lurch commented on main.cpp
> +                    // Do automatically erase flash, and make it aligned
Ahhh, I didn't realise that
```c
// Do automatically erase flash, and make it aligned
// we have to erase in whole pages
```
was intended to be two separate sentences, and not one long sentence :slightly_smiling_face:

2025-08-25 11:25 UTC, will-v-pi commented on main.cpp
> +    fos << "Copying " << (srcRemote ? "device " : "local ") << settings.filenames[0] << " to " << (destRemote ? "device " : "local ") << settings.filenames[1] << "\n";
I don’t think there’s any point removing that functionality, in case there’s a use case where you just use `picotool bdev cp` for everything - and this message makes it clear what’s happening when you do that, so if you didn’t mean to you can add a colon

2025-08-25 11:26 UTC, will-v-pi commented on main.cpp
> +        data_buf.resize(size);
Yes - should probably check the input file fits in the largest flash size (32MB currently)

2025-08-25 11:46 UTC, lurch commented on main.cpp
> +        data_buf.resize(size);
That raises an interesting point - are you able to calculate how much "free space" there is in the block device, and what happens if you try writing a file larger than this? Hopefully it doesn't just continue writing to Flash after the end of the block device?

2025-08-25 14:31 UTC, will-v-pi commented
> A thought I just had - to make this slightly easier to use, could you have `picotool` check what filename it was invoked with (e.g. like `busybox` does), and then you could have `picotool_ls`, `picotool_cat`, etc. symlinks to the `picotool` binary, and then calling `picotool_ls somedir` would do the same thing as `picotool bdev ls somedir` ? (Or if that's not possible, perhaps the picotool CMake install could add a bunch of shell scripts e.g. named `picotool_ls` which just does `picotool bdev ls $@`)

I think that might be best left to the user to do, to avoid polluting their shell (eg you might want `picotool_ls` to list devices, not use the `bdev` command) - you could also create an alias to `picotool bdev` in bashrc (which also avoids the need for underscores and therefore the shift key), so I don’t think I’ll include that is this PR

2025-08-29 09:05 UTC, will-v-pi commented on main.cpp
> +        data_buf.resize(size);
That's up to the filesystem - both LittleFS and FatFS should throw an error if there isn't enough free space on the device, but I might add a backstop to prevent writing past the end of the block device too

2025-08-29 10:35 UTC, will-v-pi commented on README.md
> +        -f, --format
> (perhaps the arg-parsing library could/should raise an error if given the same argument multiple times?)

I will leave that for a future PR

2025-08-29 10:43 UTC, will-v-pi commented on README.md
> +Print contents of file on the block device
I've pushed a change to print error strings instead of numbers, so you'd get `ERROR: LittleFS Open Error: Entry is a dir`

2025-09-01 09:17 UTC, lurch commented on main.cpp
> +            fail(ERROR_NOT_POSSIBLE, "File size %dMB is too large for flash device (max %dMB)", size / (1024 * 1024), max_size / (1024 * 1024));
Is it possible for this to (also?) check against the "block device" size, rather than just the "flash device" size? Or would that be a premature optimisation because it'll get caught by later checks anyway?

2025-09-01 09:41 UTC, lurch commented on README.md
> +        --filesystem
Is the `--filesystem` flag only needed when formatting a block-device, or are there likely to be circumstances in which the filesystem auto-deteciton doesn't work?

2025-09-01 09:46 UTC, lurch commented on README.md
> +            Format the drive if necessary (may result in data loss)
Presumably using the `--format` option in conjunction with `picotool bdev ls` will **always** return an empty directory listing? :joy:  But this makes me wonder why `--format` is an option that can be used in combination  with any other `picotool bdev` command, rather than just being a standalone `picotool bdev format` or `picotool format_bdev` command? :thinking:

2025-09-01 09:50 UTC, lurch commented on README.md
> +    Print contents of file on the block device
So I guess `picotool bdev cat main.py > main.py` effectively does the same thing as `picotool bdev cp :main.py main.py` ?

2025-09-01 09:54 UTC, lurch commented on main.cpp
> +#define BLOCK_DEVICE_PARTITION_ID 0x626C6F636B646576
Should this ID also appear somewhere in a pico-sdk header, in case 3rd-party utilities also want to use it? Or do we expect any 3rd-party utilities to just copy'n'paste this into their own source code?

2025-09-01 09:58 UTC, lurch commented on main.cpp
> +                // Check if we need to erase (ie check for non 0xff)
Does this comment need to be updated?

2025-09-01 10:05 UTC, lurch commented on main.cpp
> +    } else if (partitions) { // use first partition with id "blockdev"
It's probably a bit of an extreme edge-case, but does there need to be a mechanism for ignoring a partition named "blockdev", if you happen to have a partition with that name, but you still want to use the block device specified in the binary info?

2025-09-01 10:09 UTC, lurch commented on main.cpp
> +        fail(ERROR_CONNECTION, "No file system detected - to format the drive use `-f --filesystem <littlefs|fatfs>`");
I guess the `-f` here needs to be changed to `--format`?

2025-09-01 10:41 UTC, will-v-pi commented on lib/littlefs/README.md
> +The current files come from v2.8.2
Bumped, and seems to work fine

2025-09-01 10:43 UTC, will-v-pi commented on main.cpp
> +            fail(ERROR_NOT_POSSIBLE, "File size %dMB is too large for flash device (max %dMB)", size / (1024 * 1024), max_size / (1024 * 1024));
That'll get caught by later checks by the filesystem anyway - this check is just to prevent reading a multi-gigabyte file into memory

2025-09-01 10:45 UTC, will-v-pi commented on README.md
> +        --filesystem
With the current supported filesystems it should only be needed when formatting, but future filesystems may be harder to auto-detect so may require this flag

2025-09-01 10:53 UTC, will-v-pi commented on README.md
> +            Format the drive if necessary (may result in data loss)
I added it as a flag because of where the formatting occurs in the code - it will only format the drive if no filesystem (of the type specified by `--filesystem` if that is passed) is detected, so you could always call your first command with `--format` if you wanted to make sure you always do the command. Eg this works for both formatting new devices and updating the file on old devices:
```
picotool bdev cp main.py :/ --format --filesystem littlefs
```

2025-09-01 10:53 UTC, will-v-pi commented on README.md
> +    Print contents of file on the block device
Yes - this also allows for things like `picotool bdev cat main.py | sha256sum`

2025-09-01 10:55 UTC, will-v-pi commented on main.cpp
> +#define BLOCK_DEVICE_PARTITION_ID 0x626C6F636B646576
Yes, if it's decided that this is wanted as a way to identify block device partitions, then I'll open an SDK PR to add this to the SDK

2025-09-01 10:57 UTC, will-v-pi commented on main.cpp
> +    } else if (partitions) { // use first partition with id "blockdev"
It's not a partition named `blockdev` (the partition name can be anything), it's a partition with the 64-bit ID of the ascii characters `blockdev`, which I think is an intentional enough thing to do that we don't need to add handling for ignoring it?

2025-09-01 11:04 UTC, lurch commented on README.md
> +            Format the drive if necessary (may result in data loss)
Oh! I see now that I'd misread "Format the drive if necessary" as just "Format the drive" :facepalm: 

So I guess that means if you had a blockdevice that was already fatfs-formatted, and you wanted to explicitly reformat it, you'd need to do something like:
```
picotool bdev ls --format --filesystem littlefs
picotool bdev ls --format --filesystem fatfs
```
?

2025-09-01 11:07 UTC, will-v-pi commented on README.md
> +            Format the drive if necessary (may result in data loss)
Yes, so it probably is worth adding a separate `picotool bdev format` command to unconditionally format the block device

2026-06-16 21:27 UTC, kilograham commented on main.cpp
> +#define BLOCK_DEVICE_PARTITION_ID 0x626C6F636B646576
sounds good

2026-06-16 21:30 UTC, kilograham commented on main.cpp
> +            if (std::get<3>(partition) != BLOCK_DEVICE_PARTITION_ID) {
seems a bit mean to not let them specify the partition id (or name)

2026-06-16 21:30 UTC, kilograham commented on main.cpp
> +                if (bi_bdev.flags) {
ditto can we let them select

2026-06-16 21:31 UTC, kilograham commented on README.md
> +The `bdev` commands are for interacting with block devices in Flash. These can either be defined using binary info, or you can specify a partition to use as a block device. They work with a LittleFS
These can be defined is confusing; who is defining what, when? perhaps you mean selected not defined. Also perhaps "the commands" rather than They

2026-06-16 21:32 UTC, kilograham commented on README.md
> +        --bootsel-led <gpio>
probably a minor grumble, and maybe these are mostly applicable to all commands as you can force a reboot, and therefore there can be an activity LED, so maybe its fine... its just  abit weird that it is in target defice selection

2026-06-16 21:55 UTC, kilograham requested changes
might be worth adding some tests to make sure none of the commands delete everything ;-)

2026-06-17 11:51 UTC, will-v-pi commented on main.cpp
> +#define BLOCK_DEVICE_PARTITION_ID 0x626C6F636B646576
Done - https://github.com/raspberrypi/pico-sdk/pull/3015

2026-06-17 11:57 UTC, will-v-pi commented on README.md
> +The `bdev` commands are for interacting with block devices in Flash. These can either be defined using binary info, or you can specify a partition to use as a block device. They work with a LittleFS
```suggestion
The `bdev` commands are for interacting with block devices in Flash. The block device location can either be determined using binary info, or you can specify a partition to use as a block device. The commands work with a LittleFS filesystem, or a FatFS filesystem.
```

2026-06-17 12:03 UTC, will-v-pi commented on README.md
> +        --bootsel-led <gpio>
Yes, these are applicable to all commands that can force a reboot. Maybe the device selection could be refactored to show cleaner help text as it is the same for all commands (eg a `picotool help device_selection` command to list this help, rather than listing it out for all commands), but that would be for a different PR to do.

2026-06-17 14:00 UTC, will-v-pi commented on main.cpp
> +            if (std::get<3>(partition) != BLOCK_DEVICE_PARTITION_ID) {
Added - you can now pass the partition number, name or ID (prioritised in that order)

2026-06-18 10:07 UTC, will-v-pi commented on main.cpp
> +                if (bi_bdev.flags) {
Added options to override the flags - `--force-formattable` and `--force-writeable`

2026-06-18 10:18 UTC, lurch commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Does the `bdev ls` command really need a `--force-writeable` command, given that `ls` will presumably never result in any writes?

2026-06-18 10:37 UTC, will-v-pi commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Technically yes, in order to allow formatting a read-only drive - not useful, but technically valid

2026-06-18 10:45 UTC, will-v-pi commented on README.md
> +            Format the drive if necessary (may result in data loss)
Added

2026-06-18 10:49 UTC, will-v-pi commented on main.cpp
> +            optional_untyped_file_selection_x("dirname", 0) +
Fixed

2026-06-18 10:55 UTC, will-v-pi commented on README.md
> +Copy file to/from the block device - use :filename to indicate files on the device (eg `cp main.py :main.py` to upload to the device)
Coming back to recursive copying, I think that is trickier, as it needs a recursive walk on the host side - I think I won't add that in this PR, but maybe a future `-r` argument could be added

2026-06-18 11:02 UTC, lurch commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Huh, so merely specifying `--force-formattable` wouldn't allow a read-only drive to be formatted? That might be surprising behaviour? :thinking:

2026-06-18 11:10 UTC, will-v-pi commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
It throws a reasonable error - I think it's fine, as it requires you to stop and think even more about whether you should format the drive.
```
$ picotool bdev ls --partition-id 0 --format --force-formattable --filesystem littlefs
/
Formatting LittleFS file system
ERROR: This block device is not writeable
```

In this case, if you then pass `--force-writeable` too you still get an error, because the partition is only `NSBOOT(R)`
```
$ picotool bdev ls --partition-id 0 --format --force-formattable --force-writeable --filesystem littlefs
/
Formatting LittleFS file system
ERROR: The RP2350 device returned an error: permission failure
```

2026-06-18 11:15 UTC, will-v-pi commented
> might be worth adding some tests to make sure none of the commands delete everything ;-)

`picotool` doesn't have any on-device test infrastructure - also, the commands will delete everything if you tell them to (eg `--format --filesystem fatfs` when the device has an existing `littlefs` filesystem). I think the filesystem libraries are already tested to ensure they don't delete when they're not supposed to.

2026-06-18 14:11 UTC, lurch commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Hmmm, now that there's an explicit `bdev format` command (hooray), _maybe_ it doesn't make sense for the `bdev ls` command to have a `--format` flag, because presumably a freshly-formatted partition will always be empty? :thinking:

2026-06-18 14:32 UTC, will-v-pi commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
It has uses - you might have a provisioning system that checks for the existence of a specifc file on a board, but which needs to deal with both formatted and un-formatted boards, and is expected to output formatted boards. You could use the same command for all of them because all `bdev` commands come with the ability to format first:
```
picotool bdev ls --format --filesystem littlefs
```

2026-06-23 08:18 UTC, lurch commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
That seems a bit convoluted, but fair enough :slightly_smiling_face: 
If somebody wanted to do things "the long way round" i.e. avoiding any risk of data-loss, is there a `picotool bdev` command to check if a block device is correctly formatted or not?

2026-06-23 08:24 UTC, lurch commented
I wonder if it might be worth pulling out the 1145db7 commit into a separate PR, to minimise the unrelated README churn in **this** PR? :thinking:

2026-06-23 08:27 UTC, lurch commented on main.cpp
> +).min(0)
Do the other `opitional_...` macros (e.g. `optional_file_selection_x` and `optional_typed_file_selection_x`) also need the `.doc_non_optional(true)` to be removed?

2026-06-23 08:45 UTC, will-v-pi commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Yes, they can use any command except format, and the command will throw an error if the device wasn’t correctly formatted. If you pass `--filesystem` as well, it will throw an error if the device isn’t formatted to the specified file system.

2026-06-23 08:48 UTC, will-v-pi commented on main.cpp
> +).min(0)
No, it’s only this one - the others all have 2 options inside the brackets (file name and type), so seem to need the `doc_non_optional` to be displayed correctly - but this one only has 1 option inside the brackets, so is displayed as optional already. I’m not sure why that’s the case though…

2026-06-23 08:50 UTC, will-v-pi commented
> I wonder if it might be worth pulling out the [1145db7](https://github.com/raspberrypi/picotool/commit/1145db7bde8144d280cc3412d22e9b27c2216db0) commit into a separate PR, to minimise the unrelated README churn in **this** PR? 🤔

This PR is getting merged imminently, so I’ll leave it in this PR to avoid creating mess

2026-06-23 10:33 UTC, lurch commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
Cool, thanks. Is that behaviour worth documenting (i.e. how to check if a block device is formatted, without writing to it), or do you think that it's sufficiently obvious that people will figure it out for themselves?

2026-06-23 10:34 UTC, lurch commented on main.cpp
> +).min(0)
Fair enough - I guess this is one of those "if it works, don't touch it" things :rofl:

2026-06-23 13:07 UTC, will-v-pi commented on README.md
> +                [--filesystem <fs>] [--format] [--force-formattable] [--force-writeable] [device-selection]
I think it's clear enough?
```
$ picotool bdev ls
ERROR: No file system detected - to format the drive use `--format --filesystem <littlefs|fatfs>`

$ picotool bdev ls --filesystem littlefs
/
ERROR: LittleFS file system is corrupted - add --format flag to format it (this may result in data loss)

$ picotool bdev ls --filesystem fatfs
/
ERROR: FatFS file system is corrupted - add --format flag to format it (this may result in data loss)
```

2026-06-23 14:50 UTC, will-v-pi commented
> might be worth adding some tests to make sure none of the commands delete everything ;-)

I have added a `bdev_test.sh` script which runs some quick tests to check `rm` only removes the file it's directed to - this script requires having an RP2350 device, so must be run locally to test

2026-06-24 16:45 UTC, merged

2026-07-09 15:19 UTC, aswild commented on main.cpp
> +    return std::get<1>(*get_partition_info(con));
this operation crashes `picotool info` on RP2040 targets that don't support partition info. When `model->supports_partition_table()` returns `false`, as it does on RP2040, `get_partition_info()` returns `nullptr` and then this deref fails (either with a failed assert in debug mode, or a segfault in release mode).

This code needs to forward on `nullptr` (everywhere that calls `get_partitions` already makes sure its result is non-null before using it)

```diff
diff --git a/main.cpp b/main.cpp
index 0c3b093..b2d37e4 100644
--- a/main.cpp
+++ b/main.cpp
@@ -4670,7 +4670,11 @@ std::shared_ptr<tuple<resident_partition_t, std::shared_ptr<vector<partition_det
 }

 std::shared_ptr<vector<partition_details>> get_partitions(picoboot::connection &con) {
-    return std::get<1>(*get_partition_info(con));
+    auto info = get_partition_info(con);
+    if (info) {
+        return std::get<1>(*info);
+    }
+    return nullptr;
 }
 #endif

```

2026-07-09 17:31 UTC, lurch commented on main.cpp
> +    return std::get<1>(*get_partition_info(con));
> this operation crashes `picotool info` on RP2040 targets that don't support partition info.

Thanks for the report. Could you create a new issue please?